global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']

  - job_name: 'zookeeper'
    static_configs:
      - targets: ['zookeeper:2181']

  - job_name: 'node-producer'
    static_configs:
      - targets: ['node-producer:3333']

  - job_name: 'node-consumer'
    static_configs:
      - targets: ['node-consumer:3000']
